### ISSUE TITLE
Recognized as a virus by ESET

### ISSUE THREAD

**Issue by nakhla** [quackduck/uniclip#12] opened 2022-01-06 12:39 UTC
A suspicious object is an object (file) which has been blacklisted in cloud.
unclip file is deleted

**Comment by quackduck** [comment] 2022-01-06 15:46
This is not a bug here, but in fact in whatever antivirus software detected this as a virus

**Comment by quackduck** [comment] 2022-01-06 15:46
Windows thinks all Go binaries are malware, 😆 
I'm guessing ESET does something similar

**Comment by quackduck** [comment] 2022-04-14 00:52
Closing this

**Closed by quackduck** 2022-04-14 00:52 UTC
